version: '3.3'

services:

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./../site/:/var/www
    ports: 
      - 80:80

  php:
    build: 
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./../site/:/var/www
    ports:
      - 9011:9000

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "test123"
      MYSQL_DATABASE: "inordic"
    ports:
      - 3310:3306

  adminer:
    build:
      context: .
      dockerfile: Dockerfile-adminer
    ports:
      - 9001:8080
    volumes: 
      - ./mysql/:/docker-entrypoint-initdb.d

